[package]
name = "mosna-gui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Graphical interface of MOSNA"

[lib]
name = "mosna_gui"
path = "src/lib.rs"

[[bin]]
name = "mosna-gui"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
regex.workspace = true
serde_yaml.workspace = true

mosna-config.workspace = true
mosna-io.workspace = true
mosna-paths.workspace = true

eframe = "0.35"
egui = "0.35"
egui_extras = { version = "0.35", features = ["image"] }
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
rfd = "0.17"

[dev-dependencies]
tempfile = "3"
